name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=youyinnn&hide=HTML&langs_count=8&layout=compact&theme=rose_pine&cache_seconds=14400&hide_border=true&custom_title=Lang-frequency
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate wakatime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=youyinnn&theme=rose_pine&langs_count=10&hide=other&layout=compact&custom_title=Hours%20since:%2009/12/2021&cache_seconds=14400&hide_border=true
          path: profile/wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
